set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_LIBRARY_PATH ${CMAKE_CURRENT_LIST_DIR}/lib)
set(CMAKE_SYSROOT ${CMAKE_CURRENT_LIST_DIR}/arm-unknown-linux-musleabihf/sysroot)
set(CMAKE_C_COMPILER ${CMAKE_CURRENT_LIST_DIR}/bin/arm-unknown-linux-musleabihf-gcc)
set(CMAKE_CXX_COMPILER ${CMAKE_CURRENT_LIST_DIR}/bin/arm-unknown-linux-musleabihf-g++)
set(CMAKE_C_FLAGS "-Wno-psabi -latomic")
set(CMAKE_CXX_FLAGS "-Wno-psabi -latomic")
set(CMAKE_CXX_FLAGS_DEBUG "")
set(CMAKE_EXE_LINKER_FLAGS "-static-libgcc -static-libstdc++ -static -latomic")