set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(CMAKE_LIBRARY_PATH ${CMAKE_CURRENT_LIST_DIR}/lib)
set(CMAKE_SYSROOT ${CMAKE_CURRENT_LIST_DIR}/aarch64-unknown-linux-musl/sysroot)
set(CMAKE_C_COMPILER ${CMAKE_CURRENT_LIST_DIR}/bin/aarch64-unknown-linux-musl-gcc)
set(CMAKE_CXX_COMPILER ${CMAKE_CURRENT_LIST_DIR}/bin/aarch64-unknown-linux-musl-g++)
set(CMAKE_C_FLAGS "-Wno-psabi")
set(CMAKE_CXX_FLAGS "-Wno-psabi")
set(CMAKE_CXX_FLAGS_DEBUG "")
set(CMAKE_EXE_LINKER_FLAGS "-static-libgcc -static-libstdc++ -static")